/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crudjava;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class medico extends javax.swing.JFrame {

    conexion con1 = new conexion ();
    Connection cn =con1.conectar();
    //DefaultTableModel model;
    //Statement st;//hace la ejecucion en la base de datos
    //ResultSet rs;//trae el resultado que se hace en la base de datos
    
    public medico() {
        initComponents();
        //listar();
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMedico = new RSMaterialComponent.RSTableMetro();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        nombres = new javax.swing.JTextField();
        apellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        especialidad = new javax.swing.JTextField();
        nuevo = new javax.swing.JButton();
        insertar = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TablaMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMedicoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaMedico);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Codigo");

        jLabel2.setText("Nombres");

        jLabel3.setText("Apellidos");

        codigo.setEditable(false);

        nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresActionPerformed(evt);
            }
        });

        jLabel4.setText("Telefono");

        jLabel5.setText("Especialidad");

        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        insertar.setText("Insertar");
        insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addComponent(nuevo)
                .addGap(26, 26, 26)
                .addComponent(insertar)
                .addGap(30, 30, 30)
                .addComponent(actualizar)
                .addGap(32, 32, 32)
                .addComponent(eliminar)
                .addGap(272, 272, 272))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombres)
                            .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(131, 131, 131)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(especialidad)
                            .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(393, 393, 393)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevo)
                    .addComponent(insertar)
                    .addComponent(actualizar)
                    .addComponent(eliminar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        
        nuevo();
    }//GEN-LAST:event_nuevoActionPerformed

    private void insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActionPerformed
        
        insertar();
        mostrar();
        //listar();
        nuevo();
        
    }//GEN-LAST:event_insertarActionPerformed

    private void TablaMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMedicoMouseClicked
        int filaSeleccionada = TablaMedico.rowAtPoint(evt.getPoint());
        codigo.setText(TablaMedico.getValueAt(filaSeleccionada, 0).toString());
        nombres.setText(TablaMedico.getValueAt(filaSeleccionada, 1).toString());
        apellidos.setText(TablaMedico.getValueAt(filaSeleccionada, 2).toString());
        telefono.setText(TablaMedico.getValueAt(filaSeleccionada, 3).toString());
        especialidad.setText(TablaMedico.getValueAt(filaSeleccionada, 4).toString());
    }//GEN-LAST:event_TablaMedicoMouseClicked

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        actualizar();
        nuevo();
        mostrar();
    }//GEN-LAST:event_actualizarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        eliminar();
        mostrar();
        nuevo();
    }//GEN-LAST:event_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new medico().setVisible(true);
            }
        });
    }
    
    /*void listar (){
        String sql = "select * from medico";
        try{
            cn = con1.conectar();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            //se declara un objeto array de 5 campos
            Object[] med = new Object[5];
            model = (DefaultTableModel)TablaMedico.getModel();
            while(rs.next()){
                med[0] = rs.getInt("cod_medico");
                med[1] = rs.getString("nombres");
                med[2] = rs.getString("apellidos");
                med[3] = rs.getString("telefono");
                med[4] = rs.getString("especialidad");
                model.addRow(med);
            }
            TablaMedico.setModel(model);//pinta o llena la tabla en la vista
        }catch (Exception e){
            
        }        
    }*/
    /*void agregar(){
        
        String cod  = codigo.getText();//envia el texto que este en nombres y lo guarda en nom//nombres apellidos y correo son los nombres que se le ponen en en texfield        
        String nom  = nombres.getText();
        String apel  = apellidos.getText();
        String tel  = telefono.getText();        
        String esp  = especialidad.getText();
                
        try{
            if(nom.equals("")||apel.equals("")||tel.equals("")||esp.equals("")){
                JOptionPane.showMessageDialog(null,"No puede existir campos vacios");
                limpiar(model);
            }else{              
                String sql="insert into medico(nombres, apellidos, telefono, especialidad) values ('"+nom+"','"+apel+"','"+tel+"','"+esp+"')";
                cn=con1.conectar();
                st=cn.createStatement();
                st.executeUpdate(sql);//ejecuta la insersion de los datos en la tabla y en la bd
                JOptionPane.showMessageDialog(null,"Se insertaron los datos");
                limpiar(model);                
            }
        }catch(Exception e){        
        }
        try{
            String sql="insert into medico(nombres,apellidos, telefono, especialidad) values (?,?,?,?)";
            PreparedStatement pst=cn.prepareStatement(sql);
            
            pst.setString(1, nombres.getText());
            pst.setString(2, apellidos.getText());
            pst.setString(3, telefono.getText());
            pst.setString(4, especialidad.getText());
            
            pst.execute();
            
        }catch (Exception e){
            
        }
        
    }
    
    void limpiar(DefaultTableModel model){
        for(int i=0; i<=TablaMedico.getRowCount(); i++){
            model.removeRow(i);
            i = i-1;
        }
    }*/
    void nuevo(){
        codigo.setText("");//estos son los nombres que pusimos en el texfield
        nombres.setText("");
        apellidos.setText("");
        telefono.setText("");
        especialidad.setText("");        
        codigo.requestFocus();
    }
    
    public void insertar(){
        
        try{
            String SQL="insert into medico(nombres,apellidos,telefono,especialidad) values (?,?,?,?)";
            PreparedStatement pst=cn.clientPrepareStatement(SQL);
            
            pst.setString(1, nombres.getText());
            pst.setString(2, apellidos.getText());
            pst.setString(3, telefono.getText());
            pst.setString(4, especialidad.getText());
            if(nombres.getText().equals("")||apellidos.getText().equals("")||telefono.getText().equals("")||especialidad.getText().equals("")){
                JOptionPane.showMessageDialog(null,"No puede existir campos vacios");
            }else{
                pst.execute();
                JOptionPane.showMessageDialog(null,"Medico ingresado");
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"error de registro de medico " +e.getMessage());
        }
    }
    public void mostrar() {
        String[] titulos={"Codigo","Nombres","Apellidos","Telefono","Especialidad"};
        String[] registros = new String[5];
        
        DefaultTableModel modelo= new DefaultTableModel(null, titulos);
        
        String SQL = "select * from medico";
        
        try{
            Statement st=cn.createStatement();//hace la ejecucion en la base de datos
            ResultSet rs=st.executeQuery(SQL);//trae el resultado que se hace en la base de datos
            while(rs.next()){
                registros[0] = rs.getString("cod_medico");//columnas de la bd
                registros[1] = rs.getString("nombres");
                registros[2] = rs.getString("apellidos");
                registros[3] = rs.getString("telefono");
                registros[4] = rs.getString("especialidad");
                modelo.addRow(registros);
            }
            TablaMedico.setModel(modelo);//pinta o llena la tabla en la vista
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"error al mostrar datos " +e.getMessage());
        }
        
    }
    
    public void actualizar(){
        
        try{
            String SQL="update medico set nombres=?,apellidos=?,telefono=?,especialidad=? where cod_medico=?";
            int filaSeleccionada=TablaMedico.getSelectedRow();
            String dao=(String)TablaMedico.getValueAt(filaSeleccionada, 0);
            PreparedStatement pst=cn.clientPrepareStatement(SQL);
            
            pst.setString(1, nombres.getText());
            pst.setString(2, apellidos.getText());
            pst.setString(3, telefono.getText());
            pst.setString(4, especialidad.getText());
            pst.setString(5, dao);
            if(nombres.getText().equals("")||apellidos.getText().equals("")||telefono.getText().equals("")||especialidad.getText().equals("")){
                JOptionPane.showMessageDialog(null,"No puede existir campos vacios");
            }else{
                
                pst.execute();
                JOptionPane.showMessageDialog(null,"Medico actualizado");
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"error de actalización de medico " +e.getMessage());
        }
    }
     public void eliminar(){
        int filaSeleccionada=TablaMedico.getSelectedRow();
        
        try{
            String SQL="delete from medico where cod_medico="+TablaMedico.getValueAt(filaSeleccionada, 0);
            
            Statement st=cn.createStatement();
            int n=st.executeUpdate(SQL);
            if(n>=0){
                JOptionPane.showMessageDialog(null,"Registro eliminado " );
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"error de eliminación de medico " +e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSTableMetro TablaMedico;
    private javax.swing.JButton actualizar;
    private javax.swing.JTextField apellidos;
    private javax.swing.JTextField codigo;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField especialidad;
    private javax.swing.JButton insertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombres;
    private javax.swing.JButton nuevo;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
